[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.cache]
  paths = [
    "dist/styles",
    "node_modules"
  ]

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = ["dist"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
