[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "22.16.0" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      ".cache",
      "node_modules",
      "dist/styles"
    ]
