[build]
  publish = "dist"
  command = "NODE_OPTIONS=--max_old_space_size=10240 npm install && cross-env ELEVENTY_ENV=prod eleventy"
  functions = "src/functions"

[build.environment]
  NODE_VERSION = "22"
  ELEVENTY_ENV = "prod"
  USE_FULL_RESOLUTION_IMAGES = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
