[build]
  publish = "dist"
  command = "npm install & npm run build"
  functions = "src/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [".cache", "dist/styles", "node_modules", "dist/img/optimized"]
