[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "22.6.0", NODE_ENV = "production", NETLIFY_USE_YARN = "false" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "myhomepage/.cache",
      "dist/styles"
    ]
