[build]
  publish = "dist"
  command = "NODE_OPTIONS=--max_old_space_size=40960 npm install && npm run build"
  functions = "src/functions"

[build.environment]
  NODE_VERSION = "22.x"
  ELEVENTY_ENV = "prod"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
